### ISSUE TITLE
Booking Model

### ISSUE THREAD

**Issue by Akash-298** [Akash-298/fullstack-movie-booking-app#1]
- [x] Create the booking Model
- [x] Create the booking routes
- [x] Create the booking controller and add the functionality of get booking by id, add booking, delete booking

**Comment by Ivar246** [comment]
can you assign me this  task.. and it's better to use _.gitignore_  file to avoid  .**env** and **node_modules**  file being pushed in github and use _dotenv_ package to use  environment variable in you code.

**Comment by Akash-298** [comment]
DOne
